"""One-shot vLLM serving configuration helper.

Wraps `vllm serve`: OpenAI-compatible /v1/chat/completions the backend gateway
points at (VLLM_BASE_URL in backend/.env.example).
"""

from __future__ import annotations

from pathlib import Path

VLLM_SERVE = (
    "vllm serve ./out/merged "
    "--served-model-name conductor/mistral-7b "
    "--max-model-len 4096 "
    "--gpu-memory-utilization 0.90 "
    "--dtype bfloat16 "
    "--enable-prefix-caching "
    "--tensor-parallel-size 1 "
    "--port 8000"
)


def main() -> None:
    print("# Generated by finetune src/serve_vllm.py")
    print("export VLLM_BASE_URL=http://localhost:8000")
    print(VLLM_SERVE)


if __name__ == "__main__":
    main()